const LOGIN_REQUEST = 'LOGIN_REQUEST';
const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
const FIND_USER_REQUEST = 'DELETE_USER_REQUEST';

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
const FIND_USER_SUCCESS = 'DELETE_USER_SUCCESS';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
	LOGIN_REQUEST,
	ADD_USER_REQUEST,
	UPDATE_USER_REQUEST,
	DELETE_USER_REQUEST,
	FIND_USER_REQUEST,

	LOGIN_SUCCESS,
	ADD_USER_SUCCESS,
	UPDATE_USER_SUCCESS,
	DELETE_USER_SUCCESS,
	FIND_USER_SUCCESS,
};
